name: falsys-utilities-CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run rollup

      - name: Push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "me@falsy.me"
          git config --global user.name "Do it for fun 🕹"
          git add .
          git commit -m "Build artifacts committed by GitHub Actions"
          git push https://falsy:${{ secrets.PAT_TOKEN }}@github.com/falsy/falsys-utilities.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
